name       : ftgl
version    : 2.1.3
release    : 2
source     :
    - https://sourceforge.net/projects/ftgl/files/FTGL%20Source/2.1.3%7Erc5/ftgl-2.1.3-rc5.tar.gz/download : 5458d62122454869572d39f8aa85745fc05d5518001bcefa63bd6cbb8d26565b
license    : MIT
component  : programming
summary    : c++ library to simplify font rendering in openGL applications
description: |
    FTGL is a free cross-platform Open Source C++ library that uses Freetype2 to simplify rendering fonts in OpenGL applications. FTGL supports bitmaps, pixmaps, texture maps, outlines, polygon mesh, and extruded polygon rendering modes.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glu)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
